server:
  port: 8080
  servlet:
    context-path: /blog

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/blog"
    username: root
    password: abc123-
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "LAHeZizE3L0shb6Zv5RLvNdKz7yltiw9uPSsF4VGW9zF+bIOTH+bVvzGv+Zr+TGz"
